import type { Metadata } from "next";
import Link from "next/link";

import { SiteLogo } from "@/components/site-logo";
import { SiteFooter } from "@/components/site-footer";
import { CONTACT_EMAIL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Privacy Policy — RingDesk",
  description: "How RingDesk collects, uses, and protects your information.",
  alternates: { canonical: "https://ringdesk.co/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      {/* ⚠️ ACTION REQUIRED: Replace with Termly-generated copy before launch */}
      <main className="min-h-screen bg-white">
        <header className="mx-auto max-w-3xl px-6 pt-8">
          <SiteLogo />
        </header>

        <article className="mx-auto max-w-3xl px-6 py-16 prose-content">
          <h1 className="text-4xl font-bold tracking-tight text-[color:var(--brand-slate)] sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-[color:var(--brand-muted)]">
            Last updated: April 2026 — placeholder copy.
          </p>

          <section className="mt-10 space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight text-[color:var(--brand-slate)]">
              Information We Collect
            </h2>
            <p className="text-base leading-relaxed text-[color:var(--brand-slate)]/80">
              We collect business information you provide when signing up,
              call recordings, transcripts, and metadata generated by your AI
              receptionist, and basic site analytics from visitors to
              ringdesk.co.
            </p>
          </section>

          <section className="mt-8 space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight text-[color:var(--brand-slate)]">
              How We Use It
            </h2>
            <p className="text-base leading-relaxed text-[color:var(--brand-slate)]/80">
              We use this information to provide and improve the RingDesk
              service, configure and tune your AI receptionist, send you call
              summaries and lead alerts, and bill your subscription.
            </p>
          </section>

          <section className="mt-8 space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight text-[color:var(--brand-slate)]">
              Sharing
            </h2>
            <p className="text-base leading-relaxed text-[color:var(--brand-slate)]/80">
              We share information only with vendors who power the service
              (telephony, voice AI, payment processing) under standard data
              processing agreements. We do not sell your data.
            </p>
          </section>

          <section className="mt-8 space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight text-[color:var(--brand-slate)]">
              Your Rights
            </h2>
            <p className="text-base leading-relaxed text-[color:var(--brand-slate)]/80">
              You can request access to, correction of, or deletion of your
              data at any time by emailing us. We honor opt-out requests
              promptly.
            </p>
          </section>

          <section className="mt-8 space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight text-[color:var(--brand-slate)]">
              Contact
            </h2>
            <p className="text-base leading-relaxed text-[color:var(--brand-slate)]/80">
              Questions? Email{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="text-[color:var(--brand-indigo)] underline-offset-4 hover:underline"
              >
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>

          <p className="mt-12 text-sm">
            <Link
              href="/"
              className="text-[color:var(--brand-indigo)] hover:underline"
            >
              ← Back to home
            </Link>
          </p>
        </article>

        <SiteFooter />
      </main>
    </>
  );
}
